"""routing_map.routing_graph

Utilities to assemble a base routing graph (networkx) from build_aoi() outputs.

Design goals (dev-stage):
- Small, explicit, easy to debug.
- Robust to a few common edge formats.
- Store per-edge metadata: etype, length_km.

Expected `out` keys (from your build_aoi pipeline):
- S_nodes: pd.DataFrame with columns ['lon','lat', ...]
- S_edges: list of edges, typically [((lon,lat),(lon,lat)), ...]  OR (u_idx,v_idx) index pairs
- C_nodes: pd.DataFrame with columns ['c_id','lon','lat', ...]
- C_edges: pd.DataFrame with columns ['u','v', ...] and optionally 'length_km'
- Gate_all_cov or Gate_all: pd.DataFrame with columns ['g_id','lon','lat']
- gateB_connectors: pd.DataFrame with columns ['g_id','sea_idx', ...]

Ring-related (new):
- out['ring_graph'] is a dict containing DataFrames:
  - E_nodes, T_nodes: columns ['node_id','lon','lat', ...] (or Long/Lat)
  - E_edges, T_edges: columns ['u','v', ...] using node_id
  - ET_edges (optional): columns ['etype','u','v', ...] linking E node_id <-> T node_id
    (or ET_edges_shared / ET_edges_ramp separately)
- out['tgate_sea_connectors'] (optional): DataFrame with columns ['t_node_id','sea_idx', ...]
  (generated by routing_map.t_gate_connectors.build_tgate_sea_connectors)

Notes
-----
- Node IDs in the assembled graph are lon/lat tuples: (lon, lat) as float.
  This keeps compatibility with your existing notebook debug graph.
- Edge weights are stored under attribute 'weight' (NetworkX convention).
  When weight_unit='km', 'weight' and 'length_km' are kilometers.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Sequence, Tuple

import math

try:
    import pandas as pd
except Exception:  # pragma: no cover
    pd = None  # type: ignore

import networkx as nx

LonLat = Tuple[float, float]


# -------------------------
# Distance (dateline-safe)
# -------------------------
EARTH_R_KM = 6371.0088


def _wrap_dlon_deg(lon2: float, lon1: float) -> float:
    """Shortest signed longitude difference in degrees in [-180, 180]."""
    return (float(lon2) - float(lon1) + 180.0) % 360.0 - 180.0


def haversine_km(p1: LonLat, p2: LonLat) -> float:
    """Dateline-safe haversine distance between (lon,lat) points, in km."""
    lon1, lat1 = map(float, p1)
    lon2, lat2 = map(float, p2)

    dlon = math.radians(_wrap_dlon_deg(lon2, lon1))
    dlat = math.radians(lat2 - lat1)
    lat1r = math.radians(lat1)
    lat2r = math.radians(lat2)

    a = math.sin(dlat / 2.0) ** 2 + math.cos(lat1r) * math.cos(lat2r) * math.sin(dlon / 2.0) ** 2
    a = min(1.0, max(0.0, a))
    return 2.0 * EARTH_R_KM * math.asin(math.sqrt(a))


# -------------------------
# Helpers
# -------------------------
def _is_df(x: Any) -> bool:
    return pd is not None and isinstance(x, pd.DataFrame)


def _safe_df(out: Dict[str, Any], name: str):
    df = out.get(name)
    if df is None:
        return None
    try:
        return df if len(df) > 0 else None
    except Exception:
        return None


def _to_lonlat(p: Any) -> Optional[LonLat]:
    if isinstance(p, (tuple, list)) and len(p) >= 2:
        try:
            return (float(p[0]), float(p[1]))
        except Exception:
            return None
    return None


def _pick_lonlat_cols(df) -> Tuple[Optional[str], Optional[str]]:
    """Return (lon_col, lat_col) for df."""
    if df is None or not _is_df(df) or len(df) == 0:
        return None, None
    if "lon" in df.columns and "lat" in df.columns:
        return "lon", "lat"
    if "Long" in df.columns and "Lat" in df.columns:
        return "Long", "Lat"
    return None, None


def _sea_lonlat_by_idx(S_nodes, idx: int) -> LonLat:
    row = S_nodes.iloc[int(idx)]
    # prefer lon/lat; fallback Long/Lat
    if "lon" in S_nodes.columns and "lat" in S_nodes.columns:
        return (float(row["lon"]), float(row["lat"]))
    return (float(row["Long"]), float(row["Lat"]))


def _edge_to_lonlat(
    e: Any,
    *,
    nodes_df=None,
    idx_to_lonlat_fn=None,
) -> Optional[Tuple[LonLat, LonLat]]:
    """Return ((lon1,lat1),(lon2,lat2)) for an edge or None.

    Supports:
    - (u_idx, v_idx) with nodes_df + idx_to_lonlat_fn
    - ((lon,lat),(lon,lat))
    - ("lon,lat","lon,lat")
    """
    if not isinstance(e, (list, tuple)) or len(e) < 2:
        return None
    a, b = e[0], e[1]

    # index form
    if isinstance(a, (int,)) and isinstance(b, (int,)):
        if nodes_df is None or idx_to_lonlat_fn is None:
            return None
        try:
            return (idx_to_lonlat_fn(int(a)), idx_to_lonlat_fn(int(b)))
        except Exception:
            return None

    # lonlat tuple form
    p1 = _to_lonlat(a)
    p2 = _to_lonlat(b)
    if p1 and p2:
        return (p1, p2)

    # string "lon,lat" form
    if isinstance(a, str) and isinstance(b, str):
        try:
            lon1, lat1 = a.split(",")
            lon2, lat2 = b.split(",")
            return ((float(lon1), float(lat1)), (float(lon2), float(lat2)))
        except Exception:
            return None

    return None


# -------------------------
# Stats
# -------------------------
@dataclass
class GraphBuildStats:
    sea_edges_added: int = 0
    cc_edges_added: int = 0
    gateb_sea_edges_added: int = 0
    c_gateb_edges_added: int = 0

    # rings
    e_edges_added: int = 0
    t_edges_added: int = 0
    et_edges_added: int = 0
    tgate_sea_edges_added: int = 0


# -------------------------
# Maps
# -------------------------
def build_gate_xy(out: Dict[str, Any]) -> Dict[int, LonLat]:
    """Map g_id -> (lon,lat) from Gate_all_cov or Gate_all."""
    gate_df = _safe_df(out, "Gate_all_cov")
    if gate_df is None:
        gate_df = _safe_df(out, "Gate_all")
    if gate_df is None:
        return {}
    if "g_id" not in gate_df.columns:
        return {}
    lon_col, lat_col = _pick_lonlat_cols(gate_df)
    if not lon_col or not lat_col:
        return {}
    xy: Dict[int, LonLat] = {}
    for _, r in gate_df.iterrows():
        try:
            gid = int(r["g_id"])
            xy[gid] = (float(r[lon_col]), float(r[lat_col]))
        except Exception:
            continue
    return xy


def build_c_map(C_nodes) -> Dict[int, LonLat]:
    """Map c_id -> (lon,lat)."""
    if C_nodes is None or not _is_df(C_nodes):
        return {}
    if "c_id" not in C_nodes.columns:
        return {}
    lon_col, lat_col = _pick_lonlat_cols(C_nodes)
    if not lon_col or not lat_col:
        return {}
    out_map: Dict[int, LonLat] = {}
    for _, r in C_nodes.iterrows():
        try:
            out_map[int(r["c_id"])] = (float(r[lon_col]), float(r[lat_col]))
        except Exception:
            continue
    return out_map


def build_ring_node_map(nodes_df) -> Dict[int, LonLat]:
    """Map ring node_id -> (lon,lat)."""
    if nodes_df is None or not _is_df(nodes_df) or len(nodes_df) == 0:
        return {}
    if "node_id" not in nodes_df.columns:
        return {}
    lon_col, lat_col = _pick_lonlat_cols(nodes_df)
    if not lon_col or not lat_col:
        return {}
    out_map: Dict[int, LonLat] = {}
    for _, r in nodes_df.iterrows():
        try:
            nid = int(r["node_id"])
            out_map[nid] = (float(r[lon_col]), float(r[lat_col]))
        except Exception:
            continue
    return out_map


# -------------------------
# Graph builder
# -------------------------
def build_base_graph(
    out: Dict[str, Any],
    *,
    include_sea: bool = True,
    include_cc: bool = True,
    include_gateb_sea: bool = True,
    include_c_gateb: bool = False,
    include_rings: bool = True,
    include_et: bool = True,
    include_tgate_sea: bool = True,
    c_gateb_df=None,
    max_sea_edges: Optional[int] = None,
    max_cc_edges: Optional[int] = None,
    max_ring_edges: Optional[int] = None,
    weight_unit: str = "km",
    bbox_ll: Optional[Tuple[float, float, float, float]] = None,
) -> Tuple[nx.Graph, GraphBuildStats]:
    """Assemble a NetworkX undirected graph from `out`.

    Parameters
    ----------
    include_sea:
        Add sea edges from out['S_edges'].
    include_cc:
        Add coastal chain edges from out['C_edges'].
    include_gateb_sea:
        Add GateB->Sea connectors from out['gateB_connectors'].
    include_c_gateb:
        Add C<->GateB bridge edges (optional, if you have a df from c_gateb_connectors).
    include_rings:
        Add E/T ring edges from out['ring_graph'].
    include_et:
        Add E<->T transfer edges (shared + ramp) from out['ring_graph'].
    include_tgate_sea:
        Add Tgate->Sea connectors from out['tgate_sea_connectors'] (if present).
        This function does NOT compute connectors; it only consumes an existing df.
    max_ring_edges:
        Optional cap for ring edges per type (E/T). Mainly for debug.
    weight_unit:
        'km' (default) uses haversine_km, else 'deg' uses Euclidean degrees (debug only).
    bbox_ll:
        Optional (min_lon,min_lat,max_lon,max_lat) filter: keep edges if either endpoint in bbox.

    Returns
    -------
    (G, stats)
    """

    def in_bbox(p: LonLat) -> bool:
        if bbox_ll is None:
            return True
        x0, y0, x1, y1 = map(float, bbox_ll)
        return (x0 <= p[0] <= x1) and (y0 <= p[1] <= y1)

    def edge_keep(u: LonLat, v: LonLat) -> bool:
        if bbox_ll is None:
            return True
        return in_bbox(u) or in_bbox(v)

    def dist(u: LonLat, v: LonLat) -> float:
        if weight_unit == "km":
            return haversine_km(u, v)
        # debug: degree euclidean
        return float(math.hypot(u[0] - v[0], u[1] - v[1]))

    stats = GraphBuildStats()
    G = nx.Graph()

    # ----------------
    # Sea edges
    # ----------------
    if include_sea:
        S_nodes = _safe_df(out, "S_nodes")
        S_edges = out.get("S_edges")

        if S_edges is not None and isinstance(S_edges, (list, tuple)) and len(S_edges) > 0:
            take = S_edges
            if max_sea_edges is not None and len(take) > int(max_sea_edges):
                take = take[: int(max_sea_edges)]

            idx_to_ll = None
            if _is_df(S_nodes):
                idx_to_ll = lambda i: _sea_lonlat_by_idx(S_nodes, i)

            for e in take:
                seg = _edge_to_lonlat(e, nodes_df=S_nodes, idx_to_lonlat_fn=idx_to_ll)
                if seg is None:
                    continue
                u, v = seg
                if not edge_keep(u, v):
                    continue
                w = dist(u, v)
                G.add_edge(u, v, weight=w, length_km=(w if weight_unit == "km" else None), etype="sea")
                stats.sea_edges_added += 1

    # ----------------
    # Coastal-chain edges
    # ----------------
    if include_cc:
        C_nodes = _safe_df(out, "C_nodes")
        C_edges = _safe_df(out, "C_edges")
        c_map = build_c_map(C_nodes)

        if _is_df(C_edges) and c_map:
            cc_df = C_edges
            if max_cc_edges is not None and len(cc_df) > int(max_cc_edges):
                cc_df = cc_df.iloc[: int(max_cc_edges)]

            has_len = "length_km" in cc_df.columns

            for _, e in cc_df.iterrows():
                try:
                    p1 = c_map.get(int(e["u"]))
                    p2 = c_map.get(int(e["v"]))
                except Exception:
                    continue
                if p1 is None or p2 is None:
                    continue
                if not edge_keep(p1, p2):
                    continue

                if weight_unit == "km":
                    w = float(e["length_km"]) if has_len and e.get("length_km") is not None else haversine_km(p1, p2)
                    G.add_edge(p1, p2, weight=w, length_km=w, etype="cc")
                else:
                    w = dist(p1, p2)
                    G.add_edge(p1, p2, weight=w, length_km=None, etype="cc")

                stats.cc_edges_added += 1

    # ----------------
    # GateB -> Sea connectors
    # ----------------
    if include_gateb_sea:
        df_conn = _safe_df(out, "gateB_connectors")
        gate_xy = build_gate_xy(out)
        S_nodes = _safe_df(out, "S_nodes")

        if _is_df(df_conn) and gate_xy and _is_df(S_nodes):
            sea_col = "sea_idx" if "sea_idx" in df_conn.columns else ("s_idx" if "s_idx" in df_conn.columns else None)
            gid_col = "g_id" if "g_id" in df_conn.columns else None

            if sea_col and gid_col:
                for _, r in df_conn.iterrows():
                    try:
                        gid = int(r[gid_col])
                        if gid not in gate_xy:
                            continue
                        gb = gate_xy[gid]
                        sea = _sea_lonlat_by_idx(S_nodes, int(r[sea_col]))
                    except Exception:
                        continue
                    if not edge_keep(gb, sea):
                        continue
                    w = dist(gb, sea)
                    G.add_edge(gb, sea, weight=w, length_km=(w if weight_unit == "km" else None), etype="gb_sea")
                    stats.gateb_sea_edges_added += 1

    # ----------------
    # C <-> GateB bridge connectors (optional)
    # ----------------
    if include_c_gateb:
        df = c_gateb_df
        if df is None:
            df = _safe_df(out, "c_gateb_connectors")

        if _is_df(df):
            for _, r in df.iterrows():
                try:
                    c = (float(r.get("c_lon", r.get("lon_c"))), float(r.get("c_lat", r.get("lat_c"))))
                    g = (float(r.get("g_lon", r.get("lon_g"))), float(r.get("g_lat", r.get("lat_g"))))
                except Exception:
                    continue
                if not edge_keep(c, g):
                    continue

                if weight_unit == "km":
                    w = float(r["dist_km"]) if "dist_km" in df.columns and r.get("dist_km") is not None else haversine_km(c, g)
                    G.add_edge(c, g, weight=w, length_km=w, etype="c_gb")
                else:
                    w = float(r["dist_deg"]) if "dist_deg" in df.columns and r.get("dist_deg") is not None else dist(c, g)
                    G.add_edge(c, g, weight=w, length_km=None, etype="c_gb")

                stats.c_gateb_edges_added += 1

    # ----------------
    # Rings: E/T edges
    # ----------------
    if include_rings:
        rg = out.get("ring_graph", {}) or {}
        E_nodes = rg.get("E_nodes", None)
        T_nodes = rg.get("T_nodes", None)
        E_edges = rg.get("E_edges", None)
        T_edges = rg.get("T_edges", None)

        e_map = build_ring_node_map(E_nodes)
        t_map = build_ring_node_map(T_nodes)

        if _is_df(E_edges) and e_map:
            dfE = E_edges
            if max_ring_edges is not None and len(dfE) > int(max_ring_edges):
                dfE = dfE.iloc[: int(max_ring_edges)]
            for _, r in dfE.iterrows():
                try:
                    u_id = int(r["u"]); v_id = int(r["v"])
                    u = e_map.get(u_id); v = e_map.get(v_id)
                except Exception:
                    continue
                if u is None or v is None:
                    continue
                if not edge_keep(u, v):
                    continue
                w = dist(u, v)
                G.add_edge(u, v, weight=w, length_km=(w if weight_unit == "km" else None), etype="E_RING", ring_id=int(r.get("ring_id", -1)))
                stats.e_edges_added += 1

        if _is_df(T_edges) and t_map:
            dfT = T_edges
            if max_ring_edges is not None and len(dfT) > int(max_ring_edges):
                dfT = dfT.iloc[: int(max_ring_edges)]
            for _, r in dfT.iterrows():
                try:
                    u_id = int(r["u"]); v_id = int(r["v"])
                    u = t_map.get(u_id); v = t_map.get(v_id)
                except Exception:
                    continue
                if u is None or v is None:
                    continue
                if not edge_keep(u, v):
                    continue
                w = dist(u, v)
                G.add_edge(u, v, weight=w, length_km=(w if weight_unit == "km" else None), etype="T_RING", ring_id=int(r.get("ring_id", -1)))
                stats.t_edges_added += 1

    # ----------------
    # E <-> T transfer edges (shared + ramp)
    # ----------------
    if include_et:
        rg = out.get("ring_graph", {}) or {}
        E_nodes = rg.get("E_nodes", None)
        T_nodes = rg.get("T_nodes", None)
        e_map = build_ring_node_map(E_nodes)
        t_map = build_ring_node_map(T_nodes)

        # prefer combined ET_edges; fallback to shared+ramp
        dfET = rg.get("ET_edges", None)
        if not _is_df(dfET):
            df_shared = rg.get("ET_edges_shared", None)
            df_ramp = rg.get("ET_edges_ramp", None)
            if _is_df(df_shared) and _is_df(df_ramp):
                dfET = pd.concat([df_shared, df_ramp], ignore_index=True)
            elif _is_df(df_shared):
                dfET = df_shared
            elif _is_df(df_ramp):
                dfET = df_ramp

        if _is_df(dfET) and e_map and t_map:
            for _, r in dfET.iterrows():
                try:
                    etype = str(r.get("etype", "ET"))
                    u_id = int(r["u"]); v_id = int(r["v"])
                except Exception:
                    continue

                # Determine direction (E->T) robustly
                u_e = u_id in e_map
                v_e = v_id in e_map
                u_t = u_id in t_map
                v_t = v_id in t_map

                e_id = t_id = None
                if u_e and v_t:
                    e_id, t_id = u_id, v_id
                elif v_e and u_t:
                    e_id, t_id = v_id, u_id
                else:
                    # can't resolve endpoints
                    continue

                u = e_map.get(e_id)
                v = t_map.get(t_id)
                if u is None or v is None:
                    continue
                if not edge_keep(u, v):
                    continue

                # prefer provided cost/length if present
                w = None
                if weight_unit == "km":
                    if "cost_km" in dfET.columns and r.get("cost_km") is not None:
                        try:
                            w = float(r.get("cost_km"))
                        except Exception:
                            w = None
                    if w is None and "length_km" in dfET.columns and r.get("length_km") is not None:
                        try:
                            w = float(r.get("length_km"))
                        except Exception:
                            w = None
                if w is None:
                    w = dist(u, v)

                G.add_edge(u, v, weight=w, length_km=(w if weight_unit == "km" else None), etype=etype, ring_id=int(r.get("ring_id", -1)), reason=str(r.get("reason", "")))
                stats.et_edges_added += 1

    # ----------------
    # Tgate -> Sea connectors (consume existing df)
    # ----------------
    if include_tgate_sea:
        dfTG = _safe_df(out, "tgate_sea_connectors")
        rg = out.get("ring_graph", {}) or {}
        T_nodes = rg.get("T_nodes", None)
        t_map = build_ring_node_map(T_nodes)
        S_nodes = _safe_df(out, "S_nodes")

        if _is_df(dfTG) and t_map and _is_df(S_nodes):
            sea_col = "sea_idx" if "sea_idx" in dfTG.columns else ("s_idx" if "s_idx" in dfTG.columns else None)
            tcol = "t_node_id" if "t_node_id" in dfTG.columns else ("t_id" if "t_id" in dfTG.columns else None)
            if sea_col and tcol:
                for _, r in dfTG.iterrows():
                    try:
                        tid = int(r[tcol])
                        if tid not in t_map:
                            continue
                        tg = t_map[tid]
                        sea = _sea_lonlat_by_idx(S_nodes, int(r[sea_col]))
                    except Exception:
                        continue
                    if not edge_keep(tg, sea):
                        continue

                    w = dist(tg, sea)
                    G.add_edge(tg, sea, weight=w, length_km=(w if weight_unit == "km" else None), etype="TG_SEA", t_node_id=tid)
                    stats.tgate_sea_edges_added += 1

    return G, stats


__all__ = [
    "LonLat",
    "GraphBuildStats",
    "haversine_km",
    "build_base_graph",
    "build_gate_xy",
    "build_c_map",
    "build_ring_node_map",
]
